# SYNC-CODE-MAP.ps1
# ============================================================================
# SessionStart hook companion: detects file changes in docs/ and apps/,
# writes a change report, and updates the snapshot.
#
# Output: JSON on stdout with change summary
# Side effect: writes .claude/.code-map-changes.md if changes detected
# Side effect: updates .code-map-snapshot.json
# ============================================================================

param(
    [string]$ProjectDir = ""
)

$ErrorActionPreference = "Stop"

# Resolve project root:
# - When called with -ProjectDir (from hook), use it directly
# - Otherwise, assume script is in scripts/ and go up one level
if ($ProjectDir) {
    $ProjectRoot = (Resolve-Path $ProjectDir).Path
} else {
    $ProjectRoot = (Resolve-Path "$PSScriptRoot\..").Path
}
# Normalize: trim trailing separator for clean substring math
$ProjectRoot = $ProjectRoot.TrimEnd('\', '/')
$SnapshotFile = Join-Path $ProjectRoot ".code-map-snapshot.json"
$ChangeReportFile = Join-Path $ProjectRoot ".claude\.code-map-changes.md"

# ------------------------------------------------------------------
# 1. Collect current file listing for monitored directories
# ------------------------------------------------------------------
$WatchDirs = @(
    @{ Path = "docs"; Label = "docs/" },
    @{ Path = "apps"; Label = "apps/" }
)

$CurrentFiles = @{}
$Errors = @()

foreach ($dir in $WatchDirs) {
    $fullPath = Join-Path $ProjectRoot $dir.Path
    if (-not (Test-Path $fullPath)) {
        $Errors += "Directory not found: $fullPath"
        continue
    }
    $files = Get-ChildItem -Path $fullPath -File -Recurse -ErrorAction SilentlyContinue `
        | Where-Object { $_.FullName -notmatch '[\\/]node_modules[\\/]' -and $_.FullName -notmatch '[\\/]\.git[\\/]' -and $_.FullName -notmatch '[\\/]dist[\\/]' }
    foreach ($f in $files) {
        $relativePath = $f.FullName.Substring($ProjectRoot.Length + 1) -replace '\\', '/'
        $CurrentFiles[$relativePath] = @{
            size  = $f.Length
            mtime = $f.LastWriteTimeUtc.ToString("o")
        }
    }
}

# ------------------------------------------------------------------
# 2. Load previous snapshot (if exists)
# ------------------------------------------------------------------
$PreviousFiles = @{}
if (Test-Path $SnapshotFile) {
    try {
        $snapshot = Get-Content $SnapshotFile -Raw -Encoding UTF8 | ConvertFrom-Json
        foreach ($entry in $snapshot.files) {
            $PreviousFiles[$entry.path] = @{
                size  = $entry.size
                mtime = $entry.mtime
            }
        }
    } catch {
        # Corrupted snapshot -> treat as full rescan
        $PreviousFiles = @{}
    }
}

# ------------------------------------------------------------------
# 3. Diff - detect added, removed, modified
# ------------------------------------------------------------------
$Added    = @()
$Removed  = @()
$Modified = @()

$currentPaths  = [string[]]$CurrentFiles.Keys
$previousPaths = [string[]]$PreviousFiles.Keys

# Added: in current but not previous
foreach ($p in $currentPaths) {
    if (-not $PreviousFiles.ContainsKey($p)) {
        $Added += $p
    }
}

# Removed: in previous but not current
foreach ($p in $previousPaths) {
    if (-not $CurrentFiles.ContainsKey($p)) {
        $Removed += $p
    }
}

# Modified: in both, size or mtime differs
foreach ($p in $currentPaths) {
    if ($PreviousFiles.ContainsKey($p) -and $Added -notcontains $p) {
        $curr = $CurrentFiles[$p]
        $prev = $PreviousFiles[$p]
        if ($curr.size -ne $prev.size -or $curr.mtime -ne $prev.mtime) {
            $Modified += $p
        }
    }
}

$TotalChanges = $Added.Count + $Removed.Count + $Modified.Count

# ------------------------------------------------------------------
# 4. If changes detected, write report & update snapshot
# ------------------------------------------------------------------
if ($TotalChanges -gt 0) {
    # 4a. Write the change report
    $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $reportLines = @()
    $reportLines += "<!-- generated by scripts/sync-code-map.ps1 - do not edit manually -->"
    $reportLines += ""
    $reportLines += "## CODE_MAP.md Sync Check"
    $reportLines += ""
    $reportLines += "> Check time: $now"
    $reportLines += "> Changes: **${TotalChanges}** total (+$($Added.Count) added / -$($Removed.Count) removed / ~$($Modified.Count) modified)"
    $reportLines += ""

    if ($Added.Count -gt 0) {
        $reportLines += "### Added Files"
        $reportLines += ""
        foreach ($f in ($Added | Sort-Object)) {
            $reportLines += "- [ ] ``$f``"
        }
        $reportLines += ""
    }

    if ($Removed.Count -gt 0) {
        $reportLines += "### Removed Files"
        $reportLines += ""
        foreach ($f in ($Removed | Sort-Object)) {
            $reportLines += "- [ ] ~~``$f``~~"
        }
        $reportLines += ""
    }

    if ($Modified.Count -gt 0) {
        $reportLines += "### Modified Files"
        $reportLines += ""
        foreach ($f in ($Modified | Sort-Object)) {
            $currSize = $CurrentFiles[$f].size
            $prevSize = $PreviousFiles[$f].size
            $delta = if ($currSize -gt $prevSize) { "+$($currSize - $prevSize)" } else { "$($currSize - $prevSize)" }
            $reportLines += "- [ ] ``$f`` (${delta} bytes)"
        }
        $reportLines += ""
    }

    $reportLines += "---"
    $reportLines += "Please update CODE_MAP.md to reflect the changes above, then delete this file."

    $reportContent = $reportLines -join [System.Environment]::NewLine
    Set-Content -Path $ChangeReportFile -Value $reportContent -Encoding UTF8

    # 4b. Update snapshot
    $snapshotData = [PSCustomObject]@{
        updatedAt = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffK")
        files     = @()
    }
    $fileList = @()
    foreach ($kv in $CurrentFiles.GetEnumerator()) {
        $fileList += [PSCustomObject]@{
            path  = $kv.Key
            size  = $kv.Value.size
            mtime = $kv.Value.mtime
        }
    }
    $snapshotData.files = @($fileList | Sort-Object { $_.path })
    $snapshotData | ConvertTo-Json -Depth 3 | Set-Content -Path $SnapshotFile -Encoding UTF8

    # 4c. Output summary JSON to stdout
    $summary = [PSCustomObject]@{
        changed    = $true
        timestamp  = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffK")
        added      = $Added.Count
        removed    = $Removed.Count
        modified   = $Modified.Count
        total      = $TotalChanges
        reportFile = ".claude/.code-map-changes.md"
        errors     = $Errors
    }
    Write-Output ($summary | ConvertTo-Json -Compress)
} else {
    # No changes - cleanup stale report, ensure snapshot exists
    if (Test-Path $ChangeReportFile) {
        Remove-Item $ChangeReportFile -Force
    }

    # Create initial snapshot if missing
    if (-not (Test-Path $SnapshotFile)) {
        $snapshotData = [PSCustomObject]@{
            updatedAt = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffK")
            files     = @()
        }
        $fileList = @()
        foreach ($kv in $CurrentFiles.GetEnumerator()) {
            $fileList += [PSCustomObject]@{
                path  = $kv.Key
                size  = $kv.Value.size
                mtime = $kv.Value.mtime
            }
        }
        $snapshotData.files = @($fileList | Sort-Object { $_.path })
        $snapshotData | ConvertTo-Json -Depth 3 | Set-Content -Path $SnapshotFile -Encoding UTF8
    }

    $summary = [PSCustomObject]@{
        changed   = $false
        timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffK")
        added     = 0
        removed   = 0
        modified  = 0
        total     = 0
        errors    = $Errors
    }
    Write-Output ($summary | ConvertTo-Json -Compress)
}
